### PR TITLE
Update to ember-cli 2.13 family

### PR DESCRIPTION
**Pull request by cibernox**
I'm trying to decouple ember-exam of jQuery, and the first step is to update to the latest ember-cli & family.

The only addon I haven't updated (deliberately) is ember-qunit, since it not requires some manual initialization that I wasn't sure how to perform conditionally, since the test suite also runs in mocha.

### CODE REVIEW

**Comment by cibernox** [comment]
@trentmwillis This is a weird kind of error actually. Any idea why it's tying to replace a file all the time?

**Comment by trentmwillis** [comment]
@cibernox thanks for working on this.

> This is a weird kind of error actually. Any idea why it's tying to replace a file all the time?

Unsure what error you're referring to. Looking at Travis I only see errors related to the test-loader not being present.

**Comment by SergeAstapov** [comment]
Hi @cibernox @trentmwillis! May I help you with this PR in some way? There is already ember-cli 2.15 wheres this addon uses 2.7.
This would allow to eliminate some duplications within `node_modules` for projects that use `ember-exam`.

**Comment by trentmwillis** [comment]
@SergeAstapov feel free to open another PR.

I'm not sure what you mean by:
> This would allow to eliminate some duplications within node_modules for projects that use ember-exam.

As

**Comment by SergeAstapov** [comment]
@trentmwillis created #111

Sorry, wasn't clear - I meant `ember-cli-babel` which is listed as `dependency`.

**Comment by trentmwillis** [comment]
Ah okay, that makes sense.

I'm going to close this in favor of #111.

**Pull request closed without merging**
